name: learn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  injectable: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
